# Generated by Django 3.1.3 on 2022-06-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acreditacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante', models.CharField(max_length=300)),
                ('codigoAfiliado', models.IntegerField()),
                ('producto', models.CharField(max_length=300)),
                ('numeroDocumento', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'acreditacion',
                'managed': True,
            },
        ),
    ]
